# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Node.js Package

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    env:
        NEXT_PUBLIC_WEBSOCKET: ${{secrets.NEXT_PUBLIC_WEBSOCKET}}
        NEXT_PUBLIC_KAKOMAP_API_REST_KEY: ${{secrets.NEXT_PUBLIC_KAKOMAP_API_REST_KEY}}
        NEXT_PUBLIC_KAKOMAP_API_JAVASCRIPT_KEY: ${{secrets.NEXT_PUBLIC_KAKOMAP_API_JAVASCRIPT_KEY}}
        NEXT_PUBLIC_BACKEND_URL: ${{secrets.NEXT_PUBLIC_BACKEND_URL}}
        NEXT_PUBLIC_SPRINGBOOT_URL: ${{secrets.NEXT_PUBLIC_SPRINGBOOT_URL}}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: latest

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.PRIVATE_KEY }}

      - name: Copy files to EC2
        run: |
          scp -r -o StrictHostKeyChecking=no ./* ubuntu@${{ secrets.HOST }}:/home/ubuntu/JobGem_FE
          
      - name: Install npm
        run: npm install
        
      - name: Add user in the Docker group
        run: | 
          sudo usermod -aG docker $USER
        
      - name: reload docker session
        run: |
          sudo chmod 666 /var/run/docker.sock
          
      - name: Remove old files in EC2
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.HOST }} << 'EOF'
            rm -rf /home/ubuntu/JobGem_FE/*
          EOF

      - name: Copy files to EC2
        run: |
          scp -r -o StrictHostKeyChecking=no ./* ubuntu@${{ secrets.HOST }}:/home/ubuntu/JobGem_FE

